apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system
  namespace: elk-int
spec:
  interval: 30s
  path: ./clusters/elk-int/system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
