apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elk-int

resources:
- helm/helmrepo.yaml
- helm/helmrelease.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: elasticsearch-values
  files:
  - values.yaml=values/elastic.yaml
- name: kibana-values
  files:
  - values.yaml=values/kibana.yaml
- name: logstash-values
  files:
  - values.yaml=values/logstash.yaml
