apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: elk
  namespace: elk-int
spec:
  interval: 30s
  path: ./clusters/my-cluster/elk-int/elk
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  comfigMapGenerator:
  - name: elasticsearch-values
    files:
    - values.yaml=./clusters/my-cluster/elk-int/elk/values/elastic.yaml
  - name: kibana-values
    files:
    - values.yaml=./clusters/my-cluster/elk-int/elk/values/kibana.yaml
  - name: logstash-values
    files:
    - values.yaml=./clusters/my-cluster/elk-int/elk/values/logstash.yaml
