apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: elk
  namespace: elk-int
spec:
  interval: 30s
  path: ./clusters/my-cluster/elk-int/elk
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
